name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libsoup-3.0-dev \
          libjavascriptcoregtk-4.1-dev \
          libgdk-pixbuf2.0-dev \
          libglib2.0-dev \
          libx11-dev \
          libxdo-dev \
          mpv \
          libmpv-dev \
          libwebkit2gtk-4.1-dev
        
    - name: Build
      run: cargo build --verbose --release
      
    - name: Run tests
      run: cargo test --verbose

    - name: Generate release tag
      id: tag
      run: |
        echo "release_tag=beta_$(date +'%Y.%m.%d_%H-%M')" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        name: Beta Build ${{ steps.tag.outputs.release_tag }}
        draft: false
        prerelease: true
        files: |
          target/release/kamiview
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
